fr:
  languageName: Français
  title: "Slows Fous de Larchant"
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Made with ❤️ by Quentin"
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Nous rejoindre"
      link: "/nous-rejoindre/"
    footer_cta:
      text: "Nous rejoindre"
      link: "/nous-rejoindre/"
    # github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "Infos"
      weight: 1
    - identifier: "qsn"
      name: "Qui sommes-nous"
      url: "/qui-sommes-nous/"
      weight: 1
      post: "Découvrez l'histoire des SlowFous."
      parent: "about"
    - identifier: "votre-avis"
      name: "Votre avis compte"
      url: "/votre-avis-compte/"
      weight: 2
      post: "On discute ?"
      parent: "about"
    - identifier: "visiteur"
      name: "Vous êtes de passage ?"
      url: "/visiteurs/"
      weight: 3
      post: "Tout savoir sur Larchant"
      parent: "about"
    - identifier: "administratif"
      name: "Documents"
      url: "/documents/"
      weight: 4
      post: "Transparence sur tous nos documents"
      parent: "about"
    - identifier: "blog"
      name: "Blog des évènements"
      url: "/blog/"
      weight: 2
    - identifier: "demo-page"
      name: "Projets"
      url: "/projets/"
      weight: 3
    - identifier: "faq"
      name: "Questions"
      url: "/faq/"
      weight: 4

    # - identifier: "example"
    #   name: "Agenda"
    #   url: "https://alarchant.fr"
    #   weight: 5
    #   params:
    #     target: "_blank"
