backend:
  name: github
  repo: quentinglorieux/Slowfous # Path to your GitHub repository
  commit_messages:
    create: Create - {{collection}} “{{slug}}”
    update: Update - {{collection}} “{{slug}}”
    delete: Delete - {{collection}} “{{slug}}”
    uploadMedia: Upload - “{{path}}”
    deleteMedia: Delete - “{{path}}”
    openAuthoring: "{{message}}"
  automatic_deployments: true

media_folder: static/img
public_folder: /public/img
show_preview_links: false
superadmin: false
# editor:
#   preview: true
collections:
  - name: "a_la_une"
    label: "A la Une"
    folder: "content/fr/a_la_une"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
       

  - name: "blog"
    label: "Blog"
    folder: "content/fr/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
       

  - name: "equipe"
    label: "Équipe"
    folder: "content/fr/equipe"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "faq"
    label: "FAQ"
    folder: "content/fr/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      # - { label: "Noindex", name: "noindex", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "projets"
    label: "Projets"
    folder: "content/fr/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Button Text", name: "buttonText", widget: "string", required: false }
      - { label: "Button Link", name: "buttonLink", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Résumé", name: "resume", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
        
  - name: "pages"
    label: "Pages"
    files:
      - file: "data/home.yaml"
        label: "Home"
        name: "home_page"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Text", name: "text", widget: "markdown" }
      - file: "content/fr/documents.md"
        label: "Documents"
        name: "documents_page"
        media_folder: /static/documents # make sure to append a slash
        public_folder: /public/documents
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/fr/qui-sommes-nous.md"
        label: "Qui sommes-nous ?"
        name: "qui_sommes_nous_page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/fr/votre-avis-compte.md"
        label: "Votre avis compte"
        name: "votre_avis_compte_page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/fr/visiteurs.md"
        label: "Vous etes de passage ?"
        name: "visiteurs_page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/fr/nous-rejoindre.md"
        label: "Nous rejoindre"
        name: "nous_rejoindre_page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }